[build]
command = 'hugo'
publish = 'public'
[build.environment]
HUGO_VERSION = '0.99.1'


[context]
[context.branch-deploy]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.deploy-preview]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.production]
[context.production.environment]
HUGO_ENV = 'production'

[[redirects]]
  from = "https://jakejares.netlify.app/*"
  to = "https://jakejares.com/:splat"
  status = 301
  force = true
 
[[redirects]]
  from = "http://jakejares.netlify.app/*"
  to = "https://jakejares.com/:splat"
  status = 301
  force = true